name: 'update pob lib'
on: 
  create:
    tags: 
      - v*

jobs:
  pod_lib_update:
    runs-on: macos-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v2

      - name: pod lib update
        uses: wlixcc/pod-lib-update-action@1.0.0
        with:
        #spec 仓库路径  
          spec_repo_url: https://github.com/wlixcc/ninja-specs.git  
        #podspec的相对路径  
          spec_file_path: /ninja-kit.podspec
